### ISSUE TITLE
Use "set -e" instead of passing -e in the shebang

### ISSUE THREAD

**Issue by sushilraje** [Azure/remote-monitoring-services-java#20] opened 2018-08-08 16:39 UTC
<a href="https://github.com/zhang-hua"><img src="https://avatars1.githubusercontent.com/u/2011059?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zhang-hua](https://github.com/zhang-hua)**
_Friday Dec 01, 2017 at 03:14 GMT_
_Originally opened as https://github.com/Azure/pcs-storage-adapter-java/issues/51_

----

# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 

When the shell script executed in Git Bash on Windows environment, it will report an error
```
/usr/bin/env: ‘bash -e’: No such file or directory
```
It can be fixed by change
```
#!/usr/bin/env bash -e
```
to
```
#!/usr/bin/env bash 
set -e
```

**Comment by ppathan** [comment] 2018-08-22 21:55
Dupe of #35

**Closed by ppathan** 2018-08-22 21:55 UTC
Labels: duplicate, storage-adapter
